# Generated by Django 3.2.5 on 2021-07-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_appraisals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grading', models.CharField(max_length=50)),
                ('luster', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='appraisals',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='appraisals',
            name='appointment',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening')], default='M', max_length=1, verbose_name='Time Of Day'),
        ),
        migrations.AlterField(
            model_name='appraisals',
            name='date',
            field=models.DateField(verbose_name='Appraisal Date'),
        ),
        migrations.AddField(
            model_name='coin',
            name='gradings',
            field=models.ManyToManyField(to='main_app.Grading'),
        ),
    ]
